### ISSUE TITLE
Ensure that return values of built-in Array methods are proxied by citrine

### ISSUE THREAD

**Issue by arnellebalane** [arnellebalane/rbjs#8]
Currently, only the return values of custom methods are being proxied by `citrine`. We want the same behavior for the return values of built-in methods to maintain consistency across operations performed on a proxied array, regardless of whether a built-in or custom method is used.

**Comment by aldnav** [comment]
@arnellebalane I'll give this a shot!

**Comment by arnellebalane** [comment]
@aldnav Cool, thanks! 👍
